# Generated by Django 5.2.4 on 2025-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
