# Generated by Django 5.2.4 on 2025-08-10 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('dob', models.DateField(default=datetime.datetime(2025, 8, 10, 13, 16, 23, 508478))),
            ],
        ),
    ]
