# Generated by Django 5.2.4 on 2025-11-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='LinkP',
        ),
    ]
