# Generated by Django 5.2.4 on 2025-10-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='clicks',
        ),
    ]
